version: '3'

services:
  engine:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/db:/var/lib/mysql"
    environment:
      MYSQL_USER: inovattion
      MYSQL_DATABASE: inovattion
      MYSQL_ROOT_PASSWORD: 2023Inovatt1on

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    restart: always
    ports:
      - "81:80"
    environment:
      PMA_HOST: inovattion
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  nginx:
    build: ./.docker/nginx
    restart: always
    ports: 
      - "80:80"
    volumes: 
      - ./:/var/www
    depends_on:
      - engine